ALTER SERVER ROLE [sysadmin] ADD MEMBER [ATTIVOCORP\kmurth];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT Service\MSSQLSERVER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [l_certSignSmDetach];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [l_certSignPolyBaseAuthorize];

